name: Build and Release
on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths:
            - 'src/**'
            - 'package.json'
            - 'bun.lockb'
            - '.github/workflows/release.yml'

permissions:
  contents: write
  packages: write

jobs:
    build-and-release:
        name: Build and Release
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v7.0.0

        # Install Bun
        - uses: oven-sh/setup-bun@v2

        # Build
        - name: Build
          run: |
            bun run build

        # Zip the dist folder
        - name: Zip Build Output
          run: |
            cd dist
            zip -qq -r ../bulk-animations.zip bulk-animations/

          # Generate file checksum
        - name: Generate Checksum
          run: |
            sha256sum bulk-animations.zip > checksum.txt

        # Create release
        - name: GH Release
          uses: softprops/action-gh-release@v3.0.1
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            files: |
                bulk-animations.zip
                checksum.txt
            tag_name: "1.4.${{github.run_number}}"
            make_latest: "true"
            name: "Release v1.4.${{github.run_number}}"
